### ISSUE TITLE
It is not working in sketch V45

### ISSUE THREAD

**Issue by swasatz** [rebelliard/sketch-plugin-lists.design#3]
Hi,
I have tried in Sketch V45, It is not working. Please resolve it ASAP.

Thanks,

**Comment by juhguu** [comment]
@swasatz same problem. :(

**Comment by rebelliard** [comment]
@juhguu did you try `v0.0.2`? I tried with Sketch 43, 45 and 46 and they all worked.

**Comment by rebelliard** [comment]
@juhguu great. Thanks for reporting your issue on this baby-phased plugin. :)
